// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobs = `-- name: ClaimJobs :many
WITH claimable AS (
    SELECT id
    FROM uppgift.jobs
    WHERE (COALESCE(cardinality($1::text[]), 0) = 0 OR queue = ANY($1::text[]))
      AND (
        (state = 'available' AND run_at <= now())
        OR
        (state = 'running' AND locked_until < now())
      )
    ORDER BY
        (state = 'running') DESC,
        run_at ASC,
        id ASC
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
),
claimed AS (
    UPDATE uppgift.jobs j
    SET state = 'running',
        locked_by = $3::text,
        locked_until = now() + (COALESCE(NULLIF(j.timeout_ms, 0), 300000) * interval '1 millisecond') + interval '30 seconds'
    FROM claimable
    WHERE j.id = claimable.id
    RETURNING j.id, j.kind, j.queue, j.payload, j.attributes, j.max_retries, j.attempt, j.timeout_ms, j.run_at, j.enqueued_at, j.unique_key
),
next_upcoming AS (
    SELECT MIN(t.next_time) AS next_run_at
    FROM (
        SELECT MIN(run_at) AS next_time
        FROM uppgift.jobs
        WHERE (COALESCE(cardinality($1::text[]), 0) = 0 OR queue = ANY($1::text[]))
          AND state = 'available'
          AND run_at > now()
        UNION ALL
        SELECT MIN(locked_until) AS next_time
        FROM uppgift.jobs
        WHERE (COALESCE(cardinality($1::text[]), 0) = 0 OR queue = ANY($1::text[]))
          AND state = 'running'
          AND locked_until > now()
    ) t
    WHERE (SELECT COUNT(*) FROM claimed) < $2::int
)
SELECT
    c.id,
    c.kind,
    c.queue,
    c.payload,
    c.attributes,
    c.max_retries,
    c.attempt,
    c.timeout_ms,
    c.run_at,
    c.enqueued_at,
    c.unique_key,
    u.next_run_at::timestamptz AS next_run_at
FROM next_upcoming u
FULL JOIN claimed c ON true
`

type ClaimJobsParams struct {
	Queues     []string
	ClaimLimit int32
	WorkerID   string
}

type ClaimJobsRow struct {
	ID         pgtype.Text
	Kind       pgtype.Text
	Queue      pgtype.Text
	Payload    []byte
	Attributes []byte
	MaxRetries pgtype.Int4
	Attempt    pgtype.Int4
	TimeoutMs  pgtype.Int8
	RunAt      pgtype.Timestamptz
	EnqueuedAt pgtype.Timestamptz
	UniqueKey  pgtype.Text
	NextRunAt  pgtype.Timestamptz
}

func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]ClaimJobsRow, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.Queues, arg.ClaimLimit, arg.WorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimJobsRow
	for rows.Next() {
		var i ClaimJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Payload,
			&i.Attributes,
			&i.MaxRetries,
			&i.Attempt,
			&i.TimeoutMs,
			&i.RunAt,
			&i.EnqueuedAt,
			&i.UniqueKey,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :execrows
DELETE FROM uppgift.jobs
WHERE id = $1 AND locked_by = $2 AND state = 'running'
`

type CompleteJobParams struct {
	ID       string
	LockedBy pgtype.Text
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const discardJob = `-- name: DiscardJob :execrows
UPDATE uppgift.jobs
SET state = 'discarded',
    last_error = $1,
    locked_by = NULL,
    locked_until = NULL
WHERE id = $2 AND locked_by = $3 AND state = 'running'
`

type DiscardJobParams struct {
	LastError pgtype.Text
	ID        string
	LockedBy  pgtype.Text
}

func (q *Queries) DiscardJob(ctx context.Context, arg DiscardJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardJob, arg.LastError, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJobs = `-- name: EnqueueJobs :exec
INSERT INTO uppgift.jobs (
    id,
    queue,
    kind,
    payload,
    attributes,
    state,
    attempt,
    max_retries,
    run_at,
    timeout_ms,
    unique_key,
    enqueued_at
)
SELECT
    t.id,
    t.queue,
    t.kind,
    t.payload,
    t.attributes,
    'available',
    0,
    t.max_retries,
    t.run_at,
    t.timeout_ms,
    NULLIF(t.unique_key, ''),
    t.enqueued_at
FROM (
    SELECT
        unnest($1::text[]) AS id,
        unnest($2::text[]) AS queue,
        unnest($3::text[]) AS kind,
        unnest($4::bytea[]) AS payload,
        unnest($5::jsonb[]) AS attributes,
        unnest($6::int[]) AS max_retries,
        unnest($7::timestamptz[]) AS run_at,
        unnest($8::bigint[]) AS timeout_ms,
        unnest($9::text[]) AS unique_key,
        unnest($10::timestamptz[]) AS enqueued_at
) t
ON CONFLICT (unique_key) WHERE unique_key IS NOT NULL AND state IN ('available', 'running') DO NOTHING
`

type EnqueueJobsParams struct {
	ID         []string
	Queue      []string
	Kind       []string
	Payload    [][]byte
	Attributes [][]byte
	MaxRetries []int32
	RunAt      []pgtype.Timestamptz
	TimeoutMs  []int64
	UniqueKey  []string
	EnqueuedAt []pgtype.Timestamptz
}

func (q *Queries) EnqueueJobs(ctx context.Context, arg EnqueueJobsParams) error {
	_, err := q.db.Exec(ctx, enqueueJobs,
		arg.ID,
		arg.Queue,
		arg.Kind,
		arg.Payload,
		arg.Attributes,
		arg.MaxRetries,
		arg.RunAt,
		arg.TimeoutMs,
		arg.UniqueKey,
		arg.EnqueuedAt,
	)
	return err
}

const failJob = `-- name: FailJob :execrows
UPDATE uppgift.jobs
SET state = 'available',
    run_at = $1,
    attempt = $2,
    last_error = $3,
    locked_by = NULL,
    locked_until = NULL
WHERE id = $4 AND locked_by = $5 AND state = 'running'
`

type FailJobParams struct {
	RunAt     time.Time
	Attempt   int32
	LastError pgtype.Text
	ID        string
	LockedBy  pgtype.Text
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob,
		arg.RunAt,
		arg.Attempt,
		arg.LastError,
		arg.ID,
		arg.LockedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyQueue = `-- name: NotifyQueue :exec
SELECT pg_notify('uppgift_events', $1)
`

func (q *Queries) NotifyQueue(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyQueue, pgNotify)
	return err
}

const purgeDiscardedJobs = `-- name: PurgeDiscardedJobs :execrows
DELETE FROM uppgift.jobs
WHERE state = 'discarded'
  AND enqueued_at < $1::timestamptz
`

func (q *Queries) PurgeDiscardedJobs(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDiscardedJobs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseBuffer = `-- name: ReleaseBuffer :exec
UPDATE uppgift.jobs
SET state = 'available',
    locked_by = NULL,
    locked_until = NULL
WHERE id = ANY($1::text[])
  AND locked_by = $2::text
  AND state = 'running'
`

type ReleaseBufferParams struct {
	Ids      []string
	WorkerID string
}

func (q *Queries) ReleaseBuffer(ctx context.Context, arg ReleaseBufferParams) error {
	_, err := q.db.Exec(ctx, releaseBuffer, arg.Ids, arg.WorkerID)
	return err
}

const snoozeJob = `-- name: SnoozeJob :execrows
UPDATE uppgift.jobs
SET state = 'available',
    run_at = $1,
    locked_by = NULL,
    locked_until = NULL
WHERE id = $2 AND locked_by = $3 AND state = 'running'
`

type SnoozeJobParams struct {
	RunAt    time.Time
	ID       string
	LockedBy pgtype.Text
}

func (q *Queries) SnoozeJob(ctx context.Context, arg SnoozeJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, snoozeJob, arg.RunAt, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
