// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/branchgrove/pogo/uppgift/driver/pgx/internal/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type UppgiftJob struct {
	ID          string
	Queue       string
	Kind        string
	Payload     []byte
	Attributes  types.Attributes
	State       string
	Attempt     int32
	MaxRetries  int32
	RunAt       time.Time
	TimeoutMs   int64
	UniqueKey   pgtype.Text
	LockedBy    pgtype.Text
	LockedUntil pgtype.Timestamptz
	EnqueuedAt  time.Time
	LastError   pgtype.Text
}
